### ISSUE TITLE
VideoWriter doesn't work in 2.5.6

### ISSUE THREAD

**Issue by scotlunsford** [dajuric/dot-imaging#1] opened 2015-10-25 19:16 UTC
After updating to version 2.5.6 the VideoWriter doesn't work. Reverting back to 2.5.4 works fine.

```
DotImaging.ImageStreamReader reader = new DotImaging.ImageDirectoryCapture(recordFolder, "*.png");
float fps = Convert.ToSingle(1 / secondsPerFrame);
DotImaging.ImageStreamWriter writer = new DotImaging.VideoWriter(fileName, viewSize, fps);
writer.Open();
foreach (var image in reader)
{
    writer.Write(image);
}
writer.Close();
```

**Comment by dajuric** [comment] 2015-10-26 12:17
Hi,

  I believe I reproduced the steps, but I am unable to reproduce the bug.
Can you provide me some information what happens ?

If you feel more comfortable we can move our conversation to e-mail (darko.juric2 [at] gmail.com) 

Best regards,
Darko

**Comment by dajuric** [comment] 2015-10-26 21:53
The problem has been fixed by adding FileReadFunction property in ImageDirectoryCapture to override image loading if necessary.

**Closed as completed by dajuric** 2015-10-26 21:53 UTC
Labels: bug
